FROM node:22.21.1-bookworm-slim

RUN corepack enable && corepack prepare pnpm@11.0.9 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install

COPY . .

EXPOSE 5000 9229 9230

CMD ["pnpm", "dev:api"]
